[phases.setup]
nixPkgs = [
  "...",
  "glib",
  "nss",
  "nspr",
  "dbus",
  "atk",
  "at-spi2-atk",
  "cups",
  "libdrm",
  "expat",
  "libxkbcommon",
  "xorg.libX11",
  "xorg.libXcomposite",
  "xorg.libXdamage",
  "xorg.libXext",
  "xorg.libXfixes",
  "xorg.libXrandr",
  "xorg.libxcb",
  "mesa",
  "cairo",
  "pango",
  "alsa-lib",
  "gtk3",
  "libgbm",
]
nixLibs = [
  "glib",
  "nss",
  "nspr",
  "dbus",
  "atk",
  "at-spi2-atk",
  "cups",
  "libdrm",
  "expat",
  "libxkbcommon",
  "xorg.libX11",
  "xorg.libXcomposite",
  "xorg.libXdamage",
  "xorg.libXext",
  "xorg.libXfixes",
  "xorg.libXrandr",
  "xorg.libxcb",
  "mesa",
  "cairo",
  "pango",
  "alsa-lib",
  "gtk3",
  "libgbm",
]