// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/homepage-variants/BentoGrid.tsx": () => import("../components/mockups/homepage-variants/BentoGrid.tsx"),
  "./components/mockups/homepage-variants/Editorial.tsx": () => import("../components/mockups/homepage-variants/Editorial.tsx"),
  "./components/mockups/homepage-variants/ProblemLed.tsx": () => import("../components/mockups/homepage-variants/ProblemLed.tsx"),
  "./components/mockups/homepage-variants/ProofFirst.tsx": () => import("../components/mockups/homepage-variants/ProofFirst.tsx")
};
